export const CHANGE_EMAIL_INPUT = "CHANGE_INPUT_ACTION";
export const CHANGE_PASSWORD_INPUT = "CHANGE_PASSWORD_INPUT";

export const LOGIN_ACTION = "LOGIN_ACTION";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
