//Auth action
export const LOGIN_ACTION = 'LOGIN_ACTION';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
//Booking action
export const FETCH_BOOKING_ACTION = 'FETCH_BOOKING_ACTION';
export const FETCH_BOOKING_SUCCESS = 'FETCH_BOOKING_SUCCESS';
export const FETCH_BOOKING_FAILURE = 'FETCH_BOOKING_FAILURE';
export const ADD_BOOKING_ACTION = 'ADD_BOOKING_ACTION';
export const ADD_BOOKING_SUCCESS = 'ADD_BOOKING_SUCCESS';
export const ADD_BOOKING_FAILURE = 'ADD_BOOKING_FAILURE';
export const FETCH_BOOKING_DETAIL_SUCCESS = 'FETCH_BOOKING_DETAIL_SUCCESS';
export const FETCH_BOOKING_DETAIL_STATUS_SUCCESS = 'FETCH_BOOKING_DETAIL_STATUS_SUCCESS';
//User action
export const FETCH_USER_ACTION = 'FETCH_USER_ACTION';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';